### ISSUE TITLE
Please create an AppData file for Back to Skool

### ISSUE THREAD

**Issue by hughsie** [skoolkid/pyskool#10]
Please consider writing and installing an AppData file with the application description and some screenshots, else Back to Skool looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

**Comment by skoolkid** [comment]
AppData file added in dfabb448f49fd0743ab258451e66d9431a3c8fb7.

More screenshots to come.
